
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-user-api
  namespace: prod
  labels:
    app: scrum  
    version: "v1"
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-user-api
  template:
    metadata:
      labels:
        app: prod-user-api 
    spec:
      affinity: 
        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-group
                operator: In
                values:                 
                - bifrost 
        
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector: 
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - scrum
              topologyKey: "kubernetes.io/hostname"
        
      restartPolicy: Always  
      containers:
        - name: scrum
          image: 912391537630.dkr.ecr.us-east-1.amazonaws.com/scrum:43
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "16m"
              memory: "160M"
            limits:
              cpu: "64m"
              memory: "256M"
          ports: 
            - name: http-80
              containerPort: 80
              protocol: TCP 
            
             
          startupProbe:
            httpGet:
              path: /api/health-check.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30   
                
          
          livenessProbe:
            httpGet:
              path: /api/health-check.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
           
          
          readinessProbe:
            httpGet:
              path: /api/health-check.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          
        

     
